function kernel = get_LaplaceKernel_imagespace(voxelSize_mm)
% kernel = get_LaplaceKernel_imagespace(voxelSize_mm)
% 
% contruct Laplace kernel in image space
   
    kernelSize_ispace = [3, 3, 3];
    kernel = zeros(kernelSize_ispace);
    h = voxelSize_mm;
    kernel(:, :, 1) = [0, 0       , 0; ...
                       0, 1/h(3)^2, 0; ...
                       0, 0       , 0];
    kernel(:, :, 2) = [0       , 1/h(1)^2                       , 0; ...
                       1/h(2)^2, -2/h(1)^2 - 2/h(2)^2 - 2/h(3)^2, 1/h(2)^2; ...
                       0       , 1/h(1)^2                       , 0];
    kernel(:, :, 3) = [0, 0       , 0; ...
                       0, 1/h(3)^2, 0; ...
                       0, 0       , 0];
end