function P = get_permMat_convention(fromCS, toCS)
    
    trafo = [lower(fromCS) '2' lower(toCS)];
    switch trafo
      case 'mat2dicom'
        P = [0 1 0; ...
             1 0 0; ...
             0 0 1];
      case 'dicom2mat'
        P = [0 1 0; ...
             1 0 0; ...
             0 0 1];
      case 'mat2itk'
        P = [0 1 0; ...
             1 0 0; ...
             0 0 1];
      case 'itk2mat'
        P = [0 1 0; ...
             1 0 0; ...
             0 0 1];
      case 'mat2nifti'
        P = [ 0 -1 0; ...
             -1  0 0; ...
              0  0 1];
      case 'nifti2mat'
        P = [ 0 -1 0; ...
             -1  0 0; ...
              0  0 1];
      case 'dicom2nifti'
        P = [-1  0 0; ...
              0 -1 0; ...
              0  0 1];
      case 'nifti2dicom'
        P = [-1  0 0; ...
              0 -1 0; ...
              0  0 1];
      case 'itk2nifti'
        P = [-1  0 0; ...
              0 -1 0; ...
              0  0 1];
      case 'nifti2itk'
        P = [-1  0 0; ...
              0 -1 0; ...
              0  0 1];
      otherwise
        error('Convention not known.')
    end

end