function h = plot_WFIparams(WFIparams)
    
    if ~isfield(WFIparams, 'voxelSize_mm')
        WFIparams.voxelSize_mm = [1, 1, 1];
    end
    if ~isfield(WFIparams, 'fatFraction_percent')
        WFIparams = get_fatFraction_percent(WFIparams);
    end
    if isfield(WFIparams, 'R2s_Hz')
        WFIparams = get_T2s_ms(WFIparams);
    else
        R2s_Hz = 0;
        T2s_ms = 0;
    end
    if ~isfield(WFIparams, 'fieldmap_Hz')
        fieldmap_Hz = 0
    end

    unpack_struct2vars(WFIparams);
    
    maxAmplitude = max(abs(water(:)));
    if strcmp(method, 'CSS')
        maxAmplitude = 200;
    end
    maxFM = max(abs(fieldmap_Hz(:)));

    
    if isfield(WFIparams, 'residual') & isfield(WFIparams, 'iterations')
        h = imagine(water, 'Window', [0, maxAmplitude], 'Name', 'water [a.u.]', 'Units', 'mm', 'Voxelsize', voxelSize_mm, ...
                    fat, 'Window', [0, maxAmplitude], 'Name', 'fat [a.u.]', 'Units', 'mm', 'Voxelsize', voxelSize_mm, ...
                    fatFraction_percent, 'Window', [-5, 105], 'Name', 'fat fraction [%]', 'Units', 'mm', 'Voxelsize', voxelSize_mm, ...   
                    fieldmap_Hz, 'Window', [-maxFM, maxFM], 'Name', 'field map [Hz]', 'Units', 'mm', 'Voxelsize', voxelSize_mm, ...
                    R2s_Hz, 'Window', [0, 300], 'Name', 'R2star map [1/s]', 'Units', 'mm', 'Voxelsize', voxelSize_mm, ...
                    T2s_ms, 'Window', [0, 100], 'Name', 'T2star map [ms]', 'Units', 'mm', 'Voxelsize', voxelSize_mm, ...
                    residual, 'Name', 'residual [a.u.]', 'Units', 'mm', 'Voxelsize', voxelSize_mm, ...
                    iterations, 'Name', 'iterations [ ]', 'Units', 'mm', 'Voxelsize', voxelSize_mm, ...
                    'Panels', [4, 2]);
    else
        if isfield(WFIparams, 'R2s_Hz') & isfield(WFIparams, 'T2s_ms')
            h = imagine(water, 'Window', [0, maxAmplitude], 'Name', 'water', 'Units', 'mm', 'Voxelsize', voxelSize_mm, ...
                        fat, 'Window', [0, maxAmplitude], 'Name', 'fat', 'Units', 'mm', 'Voxelsize', voxelSize_mm, ...
                        fatFraction_percent, 'Window', [-5, 105], 'Name', 'fat fraction', 'Units', 'mm', 'Voxelsize', voxelSize_mm, ...   
                        fieldmap_Hz, 'Window', [-maxFM, maxFM], 'Name', 'field map', 'Units', 'mm', 'Voxelsize', voxelSize_mm, ...
                        R2s_Hz, 'Window', [0, 300], 'Name', 'R2star map', 'Units', 'mm', 'Voxelsize', voxelSize_mm, ...
                        T2s_ms, 'Window', [0, 100], 'Name', 'T2star map', 'Units', 'mm', 'Voxelsize', voxelSize_mm, ...
                        'Panels', [3, 2]);
        else
            h = imagine(water, 'Window', [0, maxAmplitude], 'Name', 'water', 'Units', 'mm', 'Voxelsize', voxelSize_mm, ...
                        fat, 'Window', [0, maxAmplitude], 'Name', 'fat', 'Units', 'mm', 'Voxelsize', voxelSize_mm, ...
                        fatFraction_percent, 'Window', [-5, 105], 'Name', 'fat fraction', 'Units', 'mm', 'Voxelsize', voxelSize_mm, ...   
                        fieldmap_Hz, 'Window', [-maxFM, maxFM], 'Name', 'field map', 'Units', 'mm', 'Voxelsize', voxelSize_mm, ...
                        'Panels', [2, 2]);
        end
        set(h, 'Name', WFIparams.method);
    end
